# Generated by Django 4.2.10 on 2024-05-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_point_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='model',
            new_name='model_order',
        ),
        migrations.AddField(
            model_name='point',
            name='model_turnover',
            field=models.FileField(default=1, upload_to='upload_files/'),
            preserve_default=False,
        ),
    ]
